- name : ec2instance-playbook
  hosts: host
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: update 
      yum: name=* state=latest
    - name: Install Docker
      yum:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: latest
        update_cache: true
      docker_container:
        name: khalid-springboot
        image: khaliddinh/mysql-spring
        state: started
        recreate: yes
        exposed_ports:
          - 8080
        published_ports:
          - 8080:8080
        pull: true
        comparisons:
          image: strict

    - name: Prune everything
      community.docker.docker_prune:
        containers: true
        images: true