- name : ec2instance-playbook
  hosts: host
  become: yes
  become_user: root
  become_method: sudo
  tasks:  
    - name: show 
      shell: echo $HOSTNAME
    - name: update 
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 
    - name: install docker
      apt:
        name: docker
    - name: Re-create a container
      docker_container:
        name: khalid-springboot
        image: khaliddinh/mysql-spring
        state: started
        recreate: yes
        exposed_ports:
          - 8080
        published_ports:
          - 8080:8080
        pull: true
        comparisons:
          image: strict

    - name: Prune everything
      community.docker.docker_prune:
        containers: true
        images: true